import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "./authentication";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Excursio",
  description: "Generated by create next app",
};

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
